// A model object can be created using less values than the required ones from the model class.
// For example, if we have a model class like this:
// class User extends Model<User> {
//   final String name;
//   final String email;
//   final String password;
//   final String id;
// }
// The id in the database can be generated by the database itself, so we don't need to pass it when creating a new user.
// So we can create a user using only name, email, and password.

// This file contains the base class to represent the values needed to create entries in db.

import 'package:todo_app/core/model/model.dart';

mixin CreateModel<T extends Model> {}
